### PR TITLE
Spanish traslation

### PR DESCRIPTION
**Pull request by nukuaes**
[QTpro BS 5.0 beta_01.zip](https://github.com/raiwa/qtpro-5.0-BS/files/705478/QTpro.BS.5.0.beta_01.zip)

### CODE REVIEW

**Comment by raiwa** [comment]
Hello Lionel,

Thank you. I have for now only english language files in the package for development. Once I will have all language files prepared I'll add the spanish language files (some translations I have already, some need to be done) and you can add your spanish translations.
Thanks again
Rainer

**Comment by nukuaes** [comment]
Bon dia Rainer, de nada.

El 14 de enero de 2017 9:36:07 CET, Rainer Schmied <notifications@github.com> escribió:
>Hello Lionel,
>
>Thank you. I have for now only english language files in the package
>for development. Once I will have all language files prepared I'll add
>the spanish language files (some translations I have already, some need
>to be done) and you can add your spanish translations.
>Thanks again
>Rainer
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/raiwa/qtpro-5.0-BS/pull/1#issuecomment-272610627

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by raiwa** [comment]
Hola he preparado los ficheros del español. Està por ahora todo en inglés, si tienes algo traducido, puedes subrlo.

Gracias
Rainer

**Comment by nukuaes** [comment]
Ok, si no me aclaro te envio el zip.

**Comment by nukuaes** [comment]
Hola, he modificado los archivos que tenia pero no se si lo he cambiado 
bien en github.
Saludos

**Pull request closed without merging**
